BEGIN;
--
-- Create model Person
--
CREATE TABLE "accounts_person" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "unverified_email" varchar(254) NULL, "orcid" varchar(255) NULL, "middle_name" varchar(50) NULL, "phone" varchar(15) NULL, "address" varchar(255) NULL, "type" varchar(255) NULL, "is_verified" boolean NOT NULL, "link" varchar(2000) NULL);
CREATE TABLE "accounts_person_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "person_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_person_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "person_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model PasswordReset
--
CREATE TABLE "accounts_passwordreset" ("id" uuid NOT NULL PRIMARY KEY, "timestamp" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Organization
--
CREATE TABLE "accounts_organization" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(200) NOT NULL, "name" varchar(500) NOT NULL, "description" text NULL, "type" varchar(255) NOT NULL, "link" varchar(2000) NULL, "person_id" bigint NOT NULL UNIQUE);
--
-- Create model DataLoader
--
CREATE TABLE "core_dataloader" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "person_id" bigint NOT NULL);
--
-- Create model DataSource
--
CREATE TABLE "core_datasource" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "path" varchar(255) NULL, "url" varchar(255) NULL, "header_row" integer NULL CHECK ("header_row" >= 0), "data_start_row" integer NULL CHECK ("data_start_row" >= 0), "delimiter" varchar(1) NULL, "quote_char" varchar(1) NULL, "interval" integer NULL CHECK ("interval" >= 0), "interval_units" varchar(255) NULL, "crontab" varchar(255) NULL, "start_time" timestamp with time zone NULL, "end_time" timestamp with time zone NULL, "paused" boolean NOT NULL, "timestamp_column" varchar(255) NULL, "timestamp_format" varchar(255) NULL, "timestamp_offset" varchar(255) NULL, "data_source_thru" timestamp with time zone NULL, "last_sync_successful" boolean NULL, "last_sync_message" text NULL, "last_synced" timestamp with time zone NULL, "next_sync" timestamp with time zone NULL, "data_loader_id" uuid NULL, "person_id" bigint NOT NULL);
--
-- Create model FeatureOfInterest
--
CREATE TABLE "FeatureOfInterest" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "encodingType" varchar(255) NOT NULL, "feature" text NOT NULL);
--
-- Create model Location
--
CREATE TABLE "Location" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "encodingType" varchar(255) NOT NULL, "latitude" numeric(22, 16) NOT NULL, "longitude" numeric(22, 16) NOT NULL, "elevation_m" numeric(22, 16) NULL, "elevationDatum" varchar(255) NULL, "state" varchar(200) NULL, "county" varchar(200) NULL);
--
-- Create model Thing
--
CREATE TABLE "Thing" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(200) NOT NULL, "description" text NOT NULL, "samplingFeatureType" varchar(200) NOT NULL, "samplingFeatureCode" varchar(200) NOT NULL, "siteType" varchar(200) NOT NULL, "isPrivate" boolean NOT NULL, "dataDisclaimer" text NULL, "locationId" uuid NOT NULL UNIQUE);
--
-- Create model Unit
--
CREATE TABLE "Unit" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "symbol" varchar(255) NOT NULL, "definition" text NOT NULL, "type" varchar(255) NOT NULL, "personId" bigint NULL);
--
-- Create model Sensor
--
CREATE TABLE "Sensor" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "encodingType" varchar(255) NOT NULL, "manufacturer" varchar(255) NULL, "model" varchar(255) NULL, "modelLink" varchar(500) NULL, "methodType" varchar(100) NOT NULL, "methodLink" varchar(500) NULL, "methodCode" varchar(50) NULL, "personId" bigint NULL);
--
-- Create model ProcessingLevel
--
CREATE TABLE "ProcessingLevel" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(255) NOT NULL, "definition" text NULL, "explanation" text NULL, "personId" bigint NULL);
--
-- Create model Photo
--
CREATE TABLE "Photo" ("id" uuid NOT NULL PRIMARY KEY, "filePath" varchar(1000) NOT NULL, "link" varchar(2000) NOT NULL, "thingId" uuid NOT NULL);
--
-- Create model ObservedProperty
--
CREATE TABLE "ObservedProperty" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "definition" text NOT NULL, "description" text NOT NULL, "type" varchar(500) NOT NULL, "code" varchar(500) NOT NULL, "personId" bigint NULL);
--
-- Create model HistoricalLocation
--
CREATE TABLE "HistoricalLocation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "time" timestamp with time zone NOT NULL, "locationId" uuid NOT NULL, "thingId" uuid NOT NULL);
--
-- Create model Datastream
--
CREATE TABLE "Datastream" ("id" uuid NOT NULL PRIMARY KEY, "name" uuid NOT NULL, "description" text NOT NULL, "observationType" varchar(255) NOT NULL, "resultType" varchar(255) NOT NULL, "status" varchar(255) NULL, "sampledMedium" varchar(255) NOT NULL, "valueCount" integer NULL, "noDataValue" double precision NOT NULL, "intended_time_spacing" double precision NULL, "aggregationStatistic" varchar(255) NOT NULL, "timeAggregationInterval" double precision NOT NULL, "phenomenonBeginTime" timestamp with time zone NULL, "phenomenonEndTime" timestamp with time zone NULL, "is_visible" boolean NOT NULL, "data_source_column" varchar(255) NULL, "observed_area" varchar(255) NULL, "resultEndTime" timestamp with time zone NULL, "resultBeginTime" timestamp with time zone NULL, "data_source_id" uuid NULL, "intendedTimeSpacingUnitsId" uuid NULL, "observedPropertyId" uuid NOT NULL, "processingLevelId" uuid NOT NULL, "sensorId" uuid NOT NULL, "thingId" uuid NOT NULL, "timeAggregationIntervalUnitsId" uuid NOT NULL, "unitId" uuid NOT NULL);
--
-- Create model ThingAssociation
--
CREATE TABLE "ThingAssociation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "ownsThing" boolean NOT NULL, "followsThing" boolean NOT NULL, "isPrimaryOwner" boolean NOT NULL, "personId" bigint NOT NULL, "thingId" uuid NOT NULL);
--
-- Create model Observation
--
CREATE TABLE "Observation" ("id" uuid NOT NULL, "datastreamId" uuid NOT NULL, "featureOfInterestId" uuid NULL, "phenomenonTime" timestamptz NOT NULL, "result" float8 NOT NULL, "resultTime" timestamptz NULL, "qualityCode" varchar(255) NULL, "resultQualifiers" uuid[] NULL, CONSTRAINT "_datastream_uuid_phenomenon_time_uc" UNIQUE ("datastreamId", "phenomenonTime"), CONSTRAINT observation_pkey PRIMARY KEY ("id", "datastreamId", "phenomenonTime"), CONSTRAINT observation_datastream_id_fkey FOREIGN KEY ("datastreamId") REFERENCES public."Datastream"(id), CONSTRAINT observation_feature_of_interest_id_fkey FOREIGN KEY ("featureOfInterestId") REFERENCES public."Datastream"(id));
CREATE INDEX "accounts_person_username_173ec97a_like" ON "accounts_person" ("username" varchar_pattern_ops);
CREATE INDEX "accounts_person_email_7de6b04f_like" ON "accounts_person" ("email" varchar_pattern_ops);
ALTER TABLE "accounts_person_groups" ADD CONSTRAINT "accounts_person_groups_person_id_group_id_92ec326f_uniq" UNIQUE ("person_id", "group_id");
ALTER TABLE "accounts_person_groups" ADD CONSTRAINT "accounts_person_groups_person_id_0267a8e2_fk_accounts_person_id" FOREIGN KEY ("person_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_person_groups" ADD CONSTRAINT "accounts_person_groups_group_id_2455a92a_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_person_groups_person_id_0267a8e2" ON "accounts_person_groups" ("person_id");
CREATE INDEX "accounts_person_groups_group_id_2455a92a" ON "accounts_person_groups" ("group_id");
ALTER TABLE "accounts_person_user_permissions" ADD CONSTRAINT "accounts_person_user_per_person_id_permission_id_d2e37e5b_uniq" UNIQUE ("person_id", "permission_id");
ALTER TABLE "accounts_person_user_permissions" ADD CONSTRAINT "accounts_person_user_person_id_f01807a9_fk_accounts_" FOREIGN KEY ("person_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_person_user_permissions" ADD CONSTRAINT "accounts_person_user_permission_id_ef54d0fe_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_person_user_permissions_person_id_f01807a9" ON "accounts_person_user_permissions" ("person_id");
CREATE INDEX "accounts_person_user_permissions_permission_id_ef54d0fe" ON "accounts_person_user_permissions" ("permission_id");
ALTER TABLE "accounts_passwordreset" ADD CONSTRAINT "accounts_passwordreset_user_id_948b8566_fk_accounts_person_id" FOREIGN KEY ("user_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_organization" ADD CONSTRAINT "accounts_organization_person_id_609ab700_fk_accounts_person_id" FOREIGN KEY ("person_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_dataloader" ADD CONSTRAINT "core_dataloader_person_id_1e6949f2_fk_accounts_person_id" FOREIGN KEY ("person_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_dataloader_person_id_1e6949f2" ON "core_dataloader" ("person_id");
ALTER TABLE "core_datasource" ADD CONSTRAINT "core_datasource_data_loader_id_d0f2fe25_fk_core_dataloader_id" FOREIGN KEY ("data_loader_id") REFERENCES "core_dataloader" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_datasource" ADD CONSTRAINT "core_datasource_person_id_2f64264d_fk_accounts_person_id" FOREIGN KEY ("person_id") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_datasource_data_loader_id_d0f2fe25" ON "core_datasource" ("data_loader_id");
CREATE INDEX "core_datasource_person_id_2f64264d" ON "core_datasource" ("person_id");
ALTER TABLE "Thing" ADD CONSTRAINT "Thing_locationId_0934c238_fk_Location_id" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Unit" ADD CONSTRAINT "Unit_personId_d4808dfb_fk_accounts_person_id" FOREIGN KEY ("personId") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Unit_personId_d4808dfb" ON "Unit" ("personId");
ALTER TABLE "Sensor" ADD CONSTRAINT "Sensor_personId_60499a19_fk_accounts_person_id" FOREIGN KEY ("personId") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Sensor_personId_60499a19" ON "Sensor" ("personId");
ALTER TABLE "ProcessingLevel" ADD CONSTRAINT "ProcessingLevel_personId_98534661_fk_accounts_person_id" FOREIGN KEY ("personId") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ProcessingLevel_personId_98534661" ON "ProcessingLevel" ("personId");
ALTER TABLE "Photo" ADD CONSTRAINT "Photo_thingId_e0639f53_fk_Thing_id" FOREIGN KEY ("thingId") REFERENCES "Thing" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Photo_thingId_e0639f53" ON "Photo" ("thingId");
ALTER TABLE "ObservedProperty" ADD CONSTRAINT "ObservedProperty_personId_40f975ca_fk_accounts_person_id" FOREIGN KEY ("personId") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ObservedProperty_personId_40f975ca" ON "ObservedProperty" ("personId");
ALTER TABLE "HistoricalLocation" ADD CONSTRAINT "HistoricalLocation_locationId_f6197d8f_fk_Location_id" FOREIGN KEY ("locationId") REFERENCES "Location" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "HistoricalLocation" ADD CONSTRAINT "HistoricalLocation_thingId_e07623f9_fk_Thing_id" FOREIGN KEY ("thingId") REFERENCES "Thing" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "HistoricalLocation_locationId_f6197d8f" ON "HistoricalLocation" ("locationId");
CREATE INDEX "HistoricalLocation_thingId_e07623f9" ON "HistoricalLocation" ("thingId");
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_data_source_id_709459b1_fk_core_datasource_id" FOREIGN KEY ("data_source_id") REFERENCES "core_datasource" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_intendedTimeSpacingUnitsId_28b80da3_fk_Unit_id" FOREIGN KEY ("intendedTimeSpacingUnitsId") REFERENCES "Unit" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_observedPropertyId_6a0751bf_fk_ObservedProperty_id" FOREIGN KEY ("observedPropertyId") REFERENCES "ObservedProperty" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_processingLevelId_94a218fe_fk_ProcessingLevel_id" FOREIGN KEY ("processingLevelId") REFERENCES "ProcessingLevel" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_sensorId_c91f25d4_fk_Sensor_id" FOREIGN KEY ("sensorId") REFERENCES "Sensor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_thingId_145b9393_fk_Thing_id" FOREIGN KEY ("thingId") REFERENCES "Thing" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_timeAggregationIntervalUnitsId_963ef901_fk_Unit_id" FOREIGN KEY ("timeAggregationIntervalUnitsId") REFERENCES "Unit" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "Datastream" ADD CONSTRAINT "Datastream_unitId_db056b12_fk_Unit_id" FOREIGN KEY ("unitId") REFERENCES "Unit" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "Datastream_data_source_id_709459b1" ON "Datastream" ("data_source_id");
CREATE INDEX "Datastream_intendedTimeSpacingUnitsId_28b80da3" ON "Datastream" ("intendedTimeSpacingUnitsId");
CREATE INDEX "Datastream_observedPropertyId_6a0751bf" ON "Datastream" ("observedPropertyId");
CREATE INDEX "Datastream_processingLevelId_94a218fe" ON "Datastream" ("processingLevelId");
CREATE INDEX "Datastream_sensorId_c91f25d4" ON "Datastream" ("sensorId");
CREATE INDEX "Datastream_thingId_145b9393" ON "Datastream" ("thingId");
CREATE INDEX "Datastream_timeAggregationIntervalUnitsId_963ef901" ON "Datastream" ("timeAggregationIntervalUnitsId");
CREATE INDEX "Datastream_unitId_db056b12" ON "Datastream" ("unitId");
ALTER TABLE "ThingAssociation" ADD CONSTRAINT "ThingAssociation_thingId_personId_eaef97ca_uniq" UNIQUE ("thingId", "personId");
ALTER TABLE "ThingAssociation" ADD CONSTRAINT "ThingAssociation_personId_9a4b0f72_fk_accounts_person_id" FOREIGN KEY ("personId") REFERENCES "accounts_person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ThingAssociation" ADD CONSTRAINT "ThingAssociation_thingId_55a88c85_fk_Thing_id" FOREIGN KEY ("thingId") REFERENCES "Thing" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ThingAssociation_personId_9a4b0f72" ON "ThingAssociation" ("personId");
CREATE INDEX "ThingAssociation_thingId_55a88c85" ON "ThingAssociation" ("thingId");
CREATE EXTENSION IF NOT EXISTS timescaledb;
SELECT create_hypertable('"Observation"', 'phenomenonTime', chunk_time_interval => INTERVAL '365 day', if_not_exists => TRUE);
COMMIT;
